### ISSUE TITLE
Error while running main.py in colab

### ISSUE THREAD

**Issue by Ayush-Rai** [sjmoran/CURL#11]
**Hi! While running inference on a new test image it shows the following error:-**

> 2021-03-31 07:47:30.356841: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
> 2021-03-31 07:47:31,563 INFO ######### Parameters #########
> 2021-03-31 07:47:31,563 INFO Number of epochs: 100000
> 2021-03-31 07:47:31,563 INFO Logging directory: ./log_2021-03-31_07-47-31
> 2021-03-31 07:47:31,563 INFO Dump validation accuracy every: 25
> 2021-03-31 07:47:31,563 INFO Training image directory: /home/sjm213/adobe5k/adobe5k/
> 2021-03-31 07:47:31,563 INFO ##############################
> 2021-03-31 07:47:31,563 INFO Loading Adobe5k dataset ...
> Traceback (most recent call last):
>   File "main.py", line 353, in <module>
>     main()
>   File "main.py", line 151, in main
>     is_inference=True)
> TypeError: __init__() got an unexpected keyword argument 'is_inference'

**My input directory was in form of:-**
testing_folder
. . . input
. . . . . . left.jpg
. . . . . . right.jpg
. . . images_inference.txt

**The python command I used to run the file in colab was:-**
`python main.py --inference_img_dirpath=./testing_folder/ --checkpoint_filepath=./checkpoints/log2020-09-11_15-06-47/curl_validpsnr_25.092590592669_validloss_0.022607844322919846_epoch_30_model.pt
`

**Comment by sjmoran** [comment]
This should be resolved now, please see the latest code.
