### ISSUE TITLE
no such directory as pretrained model

### ISSUE THREAD

**Issue by RyukAD** [sjmoran/CURL#12]
Did you guys decide to remove it from the repo? 
there seems to be no info regarding this.
The error i get is: FileNotFoundError: [Errno 2] No such file or directory: './pretrained_models/curl_validpsnr_23.45627680277279_validloss_0.02825431153178215_testpsnr_23.929761817622282_testloss_0.026055289432406425_epoch_99_model.pt'

i searched the repo i did not see the pretrained model anywhere.

Thanks and hope you guys are doing well.
Regards

**Comment by sjmoran** [comment]
Pre-trained model will be uploaded soon (for Adobe 5K dataset).
