### ISSUE TITLE
Pretrained models directory is missing.

### ISSUE THREAD

**Issue by sanchit88** [sjmoran/CURL#13]
Hi, I just wanted to test out the pretrained CURL model on some test images. However, you have mentioned in the **inference** section that there must exist a **pretrained_models** directory and which should contain the following model:
* curl_validpsnr_23.45627680277279_validloss_0.02825431153178215_testpsnr_23.929761817622282_testloss_0.026055289432406425_epoch_99_model.pt

Can you please make it available? Or, update a link from where it can be downloaded.

There exists a zip file **CURL_for_RGB_images.zip** which contains two pre-trained models. However, they are not the original model, i.e., they are trained until epoch 17 and epoch 30. They have higher PSNR values than mentioned in the above model. Thanks.

**Comment by sanchit88** [comment]
I have found it. This model is in a previous commit:
https://github.com/sjmoran/CURL/commit/76100650582a3aef34706b747a1aed55d923097f

**Comment by sjmoran** [comment]
Hi, I would not recommend using those pre-trained models as they assume ProPhoto RGB colour space. A replacement pre-trained model will be upload for sRGB colour space soon.

**Comment by sanchit88** [comment]
Hi SJ, so do you know when will it be released? Thanks.
