### ISSUE TITLE
[Question] Can curve-based enhancing method handle over-exposure images correction?

### ISSUE THREAD

**Issue by CaptainEven** [sjmoran/CURL#15]

**Comment by sjmoran** [comment]
Yes, in the paper we compare directly to the DeepUPE baseline: Underexposed Photo Enhancement using Deep Illumination Estimation https://jiaya.me/papers/photoenhance_cvpr19.pdf. We find that CURL significantly outperforms DeepUPE for underexposed photo enhancement.
