### ISSUE TITLE
it seems the batch size must be 1?

### ISSUE THREAD

**Issue by zener90818** [sjmoran/CURL#18]

**Comment by sjmoran** [comment]
Hi thank you for your interest in CURL. That is correct, the code is designed for a batch size of 1, as this is typically the procedure followed in the image enhancement literature (usually you get best results with a batch size of 1, not least also you save GPU memory when working with high resolution images as well). It would be relatively straightforward to amend the code to accept a batch size greater than 1. If you do make this change, please consider contributing it to the repo as a PR.
