### ISSUE TITLE
hi,is it normal for loss 

### ISSUE THREAD

**Issue by linxinqiang90** [sjmoran/CURL#22]
@sjmoran it make me confused.could you give me some idea?
![截图_选择区域_20211014100056](https://user-images.githubusercontent.com/17329323/137238159-6f9b54b0-6d35-4e34-9bc5-41ea3914fb4c.png)

**Comment by sjmoran** [comment]
Hi, thank you for your interest in CURL. There appears to be a cliff in the loss. This should be ok. You can check the image quality to be confident that your model is learning as intended.
