### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Jinpeng-An** [sjmoran/CURL#24]
data.py was not changed , the above error is displayed.how to change data.py

**Comment by sjmoran** [comment]
Please provide more diagnostic information to replicate the issue: 1) error message including the line number where the error occurs 2) command line parameters used to invoke main.py 3) directory structure of your dataset and does it adhere to that required by data.py as outlined in the README.

**Comment by sjmoran** [comment]
Issue closed due to inactivity
