### ISSUE TITLE
Batch size > 1 version

### ISSUE THREAD

**Issue by barbodpj** [sjmoran/CURL#27]
Hi, 
I've implemented the Batch Size > 1 version of Curl here: https://github.com/barbodpj/CURL. Feel free to use it.

**Comment by learning2hash** [comment]
Fantastic work, thank you so much!

**Comment by mahdip72** [comment]
Hello,
@sjmoran 
I have create a custom repo based on this repository in which I refactored many parts of the codes as well as adding bigger batch sizes.
Also, I have added other options to the code which might be interesting in practical use cases.
[Check this repo](https://github.com/mahdip72/CURL)
