### ISSUE TITLE
Can't reproduce results

### ISSUE THREAD

**Issue by l3bjorge** [sjmoran/CURL#33]
I tried using python3 main.py --inference_img_dirpath=./adobe5k_dpe/ --checkpoint_filepath=./pretrained_models/curl_validpsnr_23.073045286204017_validloss_0.0701291635632515_testpsnr_23.584083321292365_testloss_0.061363041400909424_epoch_510_model.pt on image: 
![122918](https://user-images.githubusercontent.com/25321261/174994893-faadee7e-6afb-4d33-8933-4a81829f52d6.jpg)

The result shown in the paper is the following:
![a002](https://user-images.githubusercontent.com/25321261/174995447-04e71094-5934-4b4d-a34a-27d0065cd7b5.png)

And the one I'm getting is:
![a0002-hola_TEST_1_7_PSNR_20 422_SSIM_0 776](https://user-images.githubusercontent.com/25321261/174994599-ea7a961c-5440-4a46-aac5-6f703dfe6799.jpg)

(I changed the image names for convenience)

I don't really understand what I'm doing wrong and I would appreciate some help.
Thanks in advance!

**Comment by sjmoran** [comment]
Hi, the pre-trained model is for Adobe5k and RGB images from that collection. You are using it for Samsung S7 which is a RAW dataset. Even if you convert that RAW to RGB the image distribution will be different (e.g. dynamic range etc) and you will get the results you have obtained (e.g. darker images etc). I would recommend to re-train CURL using the raw_ted.py backbone on Samsung S7.
