### ISSUE TITLE
请教一下这块实现的原理

### ISSUE THREAD

**Issue by edvardHua** [sjmoran/CURL#36]
https://github.com/sjmoran/CURL/blob/4be9753a8063f9833423e4aa5947ae7a64b114f8/util.py#L429

@sjmoran 作者你好，非常感谢您的分享，在 apply_curve 这里，关于这个 scale 的计算我有点不太明白，为什么 scale 的值是通过多次线性加权就可以获得的，感觉也无法拟合非线性的映射关系啊

**Comment by sjmoran** [comment]
Possible to write in English and I can try and help? Thank you

**Comment by sjmoran** [comment]
Closed due to inactivity
