### ISSUE TITLE
How to perform inference on a new test image??

### ISSUE THREAD

**Issue by rushirajsherlocked** [sjmoran/CURL#5]

**Comment by woctezuma** [comment]
It looks like this part is sufficient:

https://github.com/sjmoran/CURL/blob/707162c9c96349ffbb23176212fde211fe43e81e/main.py#L108-L110

https://github.com/sjmoran/CURL/blob/707162c9c96349ffbb23176212fde211fe43e81e/main.py#L159-L189

**Comment by sjmoran** [comment]
@woctezuma @rushirajsherlocked Apologies for the delayed response. Yes there is code already as highlighted above that will permit inference on new images. In the next week or two I will upload instructions on how to do that in addition to some pre-trained weights for the Adobe5K_DPE dataset.

**Comment by rushirajsherlocked** [comment]
@sjmoran Thank you very much for the helpful response! Will test it out soon!
