### ISSUE TITLE
No pretrained models?

### ISSUE THREAD

**Issue by ash80** [sjmoran/CURL#9]
According to the README, the directory `pretrained_models` is supposed to contain a set of four CURL pre-trained models. But I couldn't find this directory in the repo.

**Comment by sjmoran** [comment]
Thank you for your interest - there is a model currently being trained for Adobe-DPE dataset. It should be ready within 1 week and will be uploaded to Github.

**Comment by zrongcheng** [comment]
Excepted it!

**Comment by shakram02** [comment]
@sjmoran Any updates?
